require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/editions", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Edition. As you add validations to Edition, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Edition.create! valid_attributes
      get editions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      edition = Edition.create! valid_attributes
      get edition_url(edition)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_edition_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      edition = Edition.create! valid_attributes
      get edit_edition_url(edition)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Edition" do
        expect {
          post editions_url, params: { edition: valid_attributes }
        }.to change(Edition, :count).by(1)
      end

      it "redirects to the created edition" do
        post editions_url, params: { edition: valid_attributes }
        expect(response).to redirect_to(edition_url(Edition.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Edition" do
        expect {
          post editions_url, params: { edition: invalid_attributes }
        }.to change(Edition, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post editions_url, params: { edition: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested edition" do
        edition = Edition.create! valid_attributes
        patch edition_url(edition), params: { edition: new_attributes }
        edition.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the edition" do
        edition = Edition.create! valid_attributes
        patch edition_url(edition), params: { edition: new_attributes }
        edition.reload
        expect(response).to redirect_to(edition_url(edition))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        edition = Edition.create! valid_attributes
        patch edition_url(edition), params: { edition: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested edition" do
      edition = Edition.create! valid_attributes
      expect {
        delete edition_url(edition)
      }.to change(Edition, :count).by(-1)
    end

    it "redirects to the editions list" do
      edition = Edition.create! valid_attributes
      delete edition_url(edition)
      expect(response).to redirect_to(editions_url)
    end
  end
end
