require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/instances", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Instance. As you add validations to Instance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Instance.create! valid_attributes
      get instances_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      instance = Instance.create! valid_attributes
      get instance_url(instance)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_instance_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      instance = Instance.create! valid_attributes
      get edit_instance_url(instance)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Instance" do
        expect {
          post instances_url, params: { instance: valid_attributes }
        }.to change(Instance, :count).by(1)
      end

      it "redirects to the created instance" do
        post instances_url, params: { instance: valid_attributes }
        expect(response).to redirect_to(instance_url(Instance.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Instance" do
        expect {
          post instances_url, params: { instance: invalid_attributes }
        }.to change(Instance, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post instances_url, params: { instance: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested instance" do
        instance = Instance.create! valid_attributes
        patch instance_url(instance), params: { instance: new_attributes }
        instance.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the instance" do
        instance = Instance.create! valid_attributes
        patch instance_url(instance), params: { instance: new_attributes }
        instance.reload
        expect(response).to redirect_to(instance_url(instance))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        instance = Instance.create! valid_attributes
        patch instance_url(instance), params: { instance: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested instance" do
      instance = Instance.create! valid_attributes
      expect {
        delete instance_url(instance)
      }.to change(Instance, :count).by(-1)
    end

    it "redirects to the instances list" do
      instance = Instance.create! valid_attributes
      delete instance_url(instance)
      expect(response).to redirect_to(instances_url)
    end
  end
end
