#Rails.application.config.assets.precompile += %w( notice.png )
#Rails.application.config.assets.precompile += %w( voaw.css )
Rails.application.config.assets.precompile += %w( gritter-close.png )
Rails.application.config.assets.precompile += %w( ie-spacer.gif )
Rails.application.config.assets.precompile += %w( favicon.ico )
Rails.application.config.assets.precompile += %w( acebook.gif )
Rails.application.config.assets.precompile += %w( acebook-tile.jpg )